package character

var DefaultSkills = [35]Skill{
	Skill{Name: "astrogation", Rank: 0, Charasteristic: "intellect", IsCareerSkill: false, Type: "general"},
	Skill{Name: "athletics", Rank: 0, Charasteristic: "brawn", IsCareerSkill: false, Type: "general"},
	Skill{Name: "charm", Rank: 0, Charasteristic: "presence", IsCareerSkill: false, Type: "general"},
	Skill{Name: "coercion", Rank: 0, Charasteristic: "willpower", IsCareerSkill: false, Type: "general"},
	Skill{Name: "computers", Rank: 0, Charasteristic: "intellect", IsCareerSkill: false, Type: "general"},
	Skill{Name: "cool", Rank: 0, Charasteristic: "presence", IsCareerSkill: false, Type: "general"},
	Skill{Name: "coordination", Rank: 0, Charasteristic: "agility", IsCareerSkill: false, Type: "general"},
	Skill{Name: "deception", Rank: 0, Charasteristic: "cunning", IsCareerSkill: false, Type: "general"},
	Skill{Name: "discipline", Rank: 0, Charasteristic: "willpower", IsCareerSkill: false, Type: "general"},
	Skill{Name: "leadership", Rank: 0, Charasteristic: "presence", IsCareerSkill: false, Type: "general"},
	Skill{Name: "mechanics", Rank: 0, Charasteristic: "intellect", IsCareerSkill: false, Type: "general"},
	Skill{Name: "medicine", Rank: 0, Charasteristic: "intellect", IsCareerSkill: false, Type: "general"},
	Skill{Name: "negotiation", Rank: 0, Charasteristic: "presence", IsCareerSkill: false, Type: "general"},
	Skill{Name: "perception", Rank: 0, Charasteristic: "cunning", IsCareerSkill: false, Type: "general"},
	Skill{Name: "piloting (planetary)", Rank: 0, Charasteristic: "agility", IsCareerSkill: false, Type: "general"},
	Skill{Name: "piloting (space)", Rank: 0, Charasteristic: "agility", IsCareerSkill: false, Type: "general"},
	Skill{Name: "resilience", Rank: 0, Charasteristic: "brawn", IsCareerSkill: false, Type: "general"},
	Skill{Name: "skulduggery", Rank: 0, Charasteristic: "brawn", IsCareerSkill: false, Type: "general"},
	Skill{Name: "stealth", Rank: 0, Charasteristic: "agility", IsCareerSkill: false, Type: "general"},
	Skill{Name: "streetwise", Rank: 0, Charasteristic: "cunning", IsCareerSkill: false, Type: "general"},
	Skill{Name: "survival", Rank: 0, Charasteristic: "cunning", IsCareerSkill: false, Type: "general"},
	Skill{Name: "vigilance", Rank: 0, Charasteristic: "willpower", IsCareerSkill: false, Type: "general"},
	Skill{Name: "brawl", Rank: 0, Charasteristic: "brawn", IsCareerSkill: false, Type: "combat"},
	Skill{Name: "gunnery", Rank: 0, Charasteristic: "agility", IsCareerSkill: false, Type: "combat"},
	Skill{Name: "lightsaber", Rank: 0, Charasteristic: "brawn", IsCareerSkill: false, Type: "combat"},
	Skill{Name: "melee", Rank: 0, Charasteristic: "brawn", IsCareerSkill: false, Type: "combat"},
	Skill{Name: "ranged (light)", Rank: 0, Charasteristic: "agility", IsCareerSkill: false, Type: "combat"},
	Skill{Name: "ranged (heavy)", Rank: 0, Charasteristic: "agility", IsCareerSkill: false, Type: "combat"},
	Skill{Name: "core worlds", Rank: 0, Charasteristic: "intellect", IsCareerSkill: false, Type: "knowledge"},
	Skill{Name: "education", Rank: 0, Charasteristic: "intellect", IsCareerSkill: false, Type: "knowledge"},
	Skill{Name: "lore", Rank: 0, Charasteristic: "intellect", IsCareerSkill: false, Type: "knowledge"},
	Skill{Name: "outer rim", Rank: 0, Charasteristic: "intellect", IsCareerSkill: false, Type: "knowledge"},
	Skill{Name: "underworld", Rank: 0, Charasteristic: "intellect", IsCareerSkill: false, Type: "knowledge"},
	Skill{Name: "warfare", Rank: 0, Charasteristic: "intellect", IsCareerSkill: false, Type: "knowledge"},
	Skill{Name: "xenology", Rank: 0, Charasteristic: "intellect", IsCareerSkill: false, Type: "knowledge"},
}
